//系统消息
export const MESSAGE_TYPE_SYSTEM = "SYSTEM";
//评论文章
export const MESSAGE_TYPE_ARTICLE_COMMENT = "ARTICLE_COMMENT";
//文章评论回复
export const MESSAGE_TYPE_ARTICLE_COMMENT_REPLY = "ARTICLE_COMMENT_REPLY";
//文章子评论回复
export const MESSAGE_TYPE_ARTICLE_SUB_COMMENT_REPLY = "ARTICLE_SUB_COMMENT_REPLY";
//文章评论@到
export const MESSAGE_TYPE_ARTICLE_COMMENT_MENTION = "ARTICLE_COMMENT_MENTION";
//文章子评论@到
export const MESSAGE_TYPE_ARTICLE_SUB_COMMENT_MENTION = "ARTICLE_SUB_COMMENT_MENTION";
//文章获赞
export const MESSAGE_TYPE_ARTICLE_AGREE = "ARTICLE_AGREE";
//文章评论获赞
export const MESSAGE_TYPE_ARTICLE_COMMENT_AGREE = "ARTICLE_COMMENT_AGREE";
//文章子评论获赞
export const MESSAGE_TYPE_ARTICLE_SUB_COMMENT_AGREE = "ARTICLE_SUB_COMMENT_AGREE";
//私信
export const MESSAGE_TYPE_PRIVATE_MESSAGE = "PRIVATE_MESSAGE";
