//系统消息
export const MESSAGE_TYPE_SYSTEM = "SYSTEM";
//评论文章
export const MESSAGE_TYPE_ARTICLE_COMMENT = "ARTICLE_COMMENT";
//文章评论回复
export const MESSAGE_TYPE_ARTICLE_COMMENT_REPLY = "ARTICLE_COMMENT_REPLY";
//文章子评论回复
export const MESSAGE_TYPE_ARTICLE_SUB_COMMENT_REPLY = "ARTICLE_SUB_COMMENT_REPLY";
//文章评论@到
export const MESSAGE_TYPE_ARTICLE_COMMENT_MENTION = "ARTICLE_COMMENT_MENTION";
//文章子评论@到
export const MESSAGE_TYPE_ARTICLE_SUB_COMMENT_MENTION = "ARTICLE_SUB_COMMENT_MENTION";
//文章获赞
export const MESSAGE_TYPE_ARTICLE_AGREE = "ARTICLE_AGREE";
//文章评论获赞
export const MESSAGE_TYPE_ARTICLE_COMMENT_AGREE = "ARTICLE_COMMENT_AGREE";
//文章子评论获赞
export const MESSAGE_TYPE_ARTICLE_SUB_COMMENT_AGREE = "ARTICLE_SUB_COMMENT_AGREE";

//留言
export const MESSAGE_TYPE_LEFT_MESSAGE = "LEFT_MESSAGE";
//留言回复
export const MESSAGE_TYPE_LEFT_MESSAGE_REPLY = "LEFT_MESSAGE_REPLY";
//留言子回复
export const MESSAGE_TYPE_LEFT_MESSAGE_SUB_REPLY = "LEFT_MESSAGE_SUB_REPLY";
//留言@到
export const MESSAGE_TYPE_LEFT_MESSAGE_MENTION = "LEFT_MESSAGE_MENTION";
//留言回复@到
export const MESSAGE_TYPE_LEFT_MESSAGE_REPLY_MENTION = "LEFT_MESSAGE_REPLY_MENTION";
//留言点赞
export const MESSAGE_TYPE_LEFT_MESSAGE_AGREE = "LEFT_MESSAGE_AGREE";
//留言回复点赞
export const MESSAGE_TYPE_LEFT_MESSAGE_REPLY_AGREE = "LEFT_MESSAGE_REPLY_AGREE";

//私信
export const MESSAGE_TYPE_PRIVATE_MESSAGE = "PRIVATE_MESSAGE";
